// Generated by gencpp from file RoboCompPlaneROS/setWidth.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_SETWIDTH_H
#define ROBOCOMPPLANEROS_MESSAGE_SETWIDTH_H

#include <ros/service_traits.h>


#include <RoboCompPlaneROS/setWidthRequest.h>
#include <RoboCompPlaneROS/setWidthResponse.h>


namespace RoboCompPlaneROS
{

struct setWidth
{

typedef setWidthRequest Request;
typedef setWidthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setWidth
} // namespace RoboCompPlaneROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompPlaneROS::setWidth > {
  static const char* value()
  {
    return "47c8ba77e2925cb2030a1992cc76935c";
  }

  static const char* value(const ::RoboCompPlaneROS::setWidth&) { return value(); }
};

template<>
struct DataType< ::RoboCompPlaneROS::setWidth > {
  static const char* value()
  {
    return "RoboCompPlaneROS/setWidth";
  }

  static const char* value(const ::RoboCompPlaneROS::setWidth&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompPlaneROS::setWidthRequest> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setWidth > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setWidthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setWidth >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setWidthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setWidthRequest> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setWidth > 
template<>
struct DataType< ::RoboCompPlaneROS::setWidthRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setWidth >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setWidthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompPlaneROS::setWidthResponse> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setWidth > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setWidthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setWidth >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setWidthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setWidthResponse> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setWidth > 
template<>
struct DataType< ::RoboCompPlaneROS::setWidthResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setWidth >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setWidthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_SETWIDTH_H
