// Generated by gencpp from file RoboCompPlaneROS/addPoint.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_ADDPOINT_H
#define ROBOCOMPPLANEROS_MESSAGE_ADDPOINT_H

#include <ros/service_traits.h>


#include <RoboCompPlaneROS/addPointRequest.h>
#include <RoboCompPlaneROS/addPointResponse.h>


namespace RoboCompPlaneROS
{

struct addPoint
{

typedef addPointRequest Request;
typedef addPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addPoint
} // namespace RoboCompPlaneROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompPlaneROS::addPoint > {
  static const char* value()
  {
    return "459c08be3d3265d9322b26f0cd3334a0";
  }

  static const char* value(const ::RoboCompPlaneROS::addPoint&) { return value(); }
};

template<>
struct DataType< ::RoboCompPlaneROS::addPoint > {
  static const char* value()
  {
    return "RoboCompPlaneROS/addPoint";
  }

  static const char* value(const ::RoboCompPlaneROS::addPoint&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompPlaneROS::addPointRequest> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::addPoint > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::addPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::addPoint >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::addPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::addPointRequest> should match 
// service_traits::DataType< ::RoboCompPlaneROS::addPoint > 
template<>
struct DataType< ::RoboCompPlaneROS::addPointRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::addPoint >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::addPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompPlaneROS::addPointResponse> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::addPoint > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::addPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::addPoint >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::addPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::addPointResponse> should match 
// service_traits::DataType< ::RoboCompPlaneROS::addPoint > 
template<>
struct DataType< ::RoboCompPlaneROS::addPointResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::addPoint >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::addPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_ADDPOINT_H
