// Generated by gencpp from file RoboCompPlaneROS/addPointRequest.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_ADDPOINTREQUEST_H
#define ROBOCOMPPLANEROS_MESSAGE_ADDPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompPlaneROS/PointXY.h>

namespace RoboCompPlaneROS
{
template <class ContainerAllocator>
struct addPointRequest_
{
  typedef addPointRequest_<ContainerAllocator> Type;

  addPointRequest_()
    : point()  {
    }
  addPointRequest_(const ContainerAllocator& _alloc)
    : point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::RoboCompPlaneROS::PointXY_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addPointRequest_

typedef ::RoboCompPlaneROS::addPointRequest_<std::allocator<void> > addPointRequest;

typedef boost::shared_ptr< ::RoboCompPlaneROS::addPointRequest > addPointRequestPtr;
typedef boost::shared_ptr< ::RoboCompPlaneROS::addPointRequest const> addPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RoboCompPlaneROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_srvs': ['/opt/ros/melodic/share/std_srv/srv'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/msg'], 'RoboCompPlaneROS': ['./src']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3259e377d82a659e3164447ef8d92b06";
  }

  static const char* value(const ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3259e377d82a659eULL;
  static const uint64_t static_value2 = 0x3164447ef8d92b06ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompPlaneROS/addPointRequest";
  }

  static const char* value(const ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PointXY point\n\
\n\
================================================================================\n\
MSG: RoboCompPlaneROS/PointXY\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompPlaneROS::addPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::RoboCompPlaneROS::PointXY_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_ADDPOINTREQUEST_H
