// Generated by gencpp from file RoboCompPlaneROS/setHeightResponse.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTRESPONSE_H
#define ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompPlaneROS/Dimensions.h>

namespace RoboCompPlaneROS
{
template <class ContainerAllocator>
struct setHeightResponse_
{
  typedef setHeightResponse_<ContainerAllocator> Type;

  setHeightResponse_()
    : dims()  {
    }
  setHeightResponse_(const ContainerAllocator& _alloc)
    : dims(_alloc)  {
  (void)_alloc;
    }



   typedef  ::RoboCompPlaneROS::Dimensions_<ContainerAllocator>  _dims_type;
  _dims_type dims;





  typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setHeightResponse_

typedef ::RoboCompPlaneROS::setHeightResponse_<std::allocator<void> > setHeightResponse;

typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightResponse > setHeightResponsePtr;
typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightResponse const> setHeightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RoboCompPlaneROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_srvs': ['/opt/ros/melodic/share/std_srv/srv'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/msg'], 'RoboCompPlaneROS': ['./src']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13e083124bdeb3c1605a4e74a94525df";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13e083124bdeb3c1ULL;
  static const uint64_t static_value2 = 0x605a4e74a94525dfULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompPlaneROS/setHeightResponse";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Dimensions dims\n\
\n\
\n\
================================================================================\n\
MSG: RoboCompPlaneROS/Dimensions\n\
int32 width\n\
int32 height\n\
";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dims);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setHeightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompPlaneROS::setHeightResponse_<ContainerAllocator>& v)
  {
    s << indent << "dims: ";
    s << std::endl;
    Printer< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >::stream(s, indent + "  ", v.dims);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTRESPONSE_H
