// Generated by gencpp from file RoboCompPlaneROS/setHeight.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_SETHEIGHT_H
#define ROBOCOMPPLANEROS_MESSAGE_SETHEIGHT_H

#include <ros/service_traits.h>


#include <RoboCompPlaneROS/setHeightRequest.h>
#include <RoboCompPlaneROS/setHeightResponse.h>


namespace RoboCompPlaneROS
{

struct setHeight
{

typedef setHeightRequest Request;
typedef setHeightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setHeight
} // namespace RoboCompPlaneROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompPlaneROS::setHeight > {
  static const char* value()
  {
    return "5bb493a7bd332a5999216072e7290e06";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeight&) { return value(); }
};

template<>
struct DataType< ::RoboCompPlaneROS::setHeight > {
  static const char* value()
  {
    return "RoboCompPlaneROS/setHeight";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeight&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompPlaneROS::setHeightRequest> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setHeight > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setHeightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setHeight >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setHeightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setHeightRequest> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setHeight > 
template<>
struct DataType< ::RoboCompPlaneROS::setHeightRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setHeight >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setHeightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompPlaneROS::setHeightResponse> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setHeight > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setHeightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setHeight >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setHeightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setHeightResponse> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setHeight > 
template<>
struct DataType< ::RoboCompPlaneROS::setHeightResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setHeight >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setHeightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_SETHEIGHT_H
