// Generated by gencpp from file RoboCompPlaneROS/setHeightRequest.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTREQUEST_H
#define ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RoboCompPlaneROS
{
template <class ContainerAllocator>
struct setHeightRequest_
{
  typedef setHeightRequest_<ContainerAllocator> Type;

  setHeightRequest_()
    : height(0)  {
    }
  setHeightRequest_(const ContainerAllocator& _alloc)
    : height(0)  {
  (void)_alloc;
    }



   typedef int32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setHeightRequest_

typedef ::RoboCompPlaneROS::setHeightRequest_<std::allocator<void> > setHeightRequest;

typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightRequest > setHeightRequestPtr;
typedef boost::shared_ptr< ::RoboCompPlaneROS::setHeightRequest const> setHeightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RoboCompPlaneROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_srvs': ['/opt/ros/melodic/share/std_srv/srv'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/msg'], 'RoboCompPlaneROS': ['./src']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0f82893e3072adec529e8691cb2ae68";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0f82893e3072adeULL;
  static const uint64_t static_value2 = 0xc529e8691cb2ae68ULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompPlaneROS/setHeightRequest";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 height\n\
";
  }

  static const char* value(const ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setHeightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompPlaneROS::setHeightRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_SETHEIGHTREQUEST_H
