// Generated by gencpp from file RoboCompPlaneROS/setName.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_SETNAME_H
#define ROBOCOMPPLANEROS_MESSAGE_SETNAME_H

#include <ros/service_traits.h>


#include <RoboCompPlaneROS/setNameRequest.h>
#include <RoboCompPlaneROS/setNameResponse.h>


namespace RoboCompPlaneROS
{

struct setName
{

typedef setNameRequest Request;
typedef setNameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setName
} // namespace RoboCompPlaneROS


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::RoboCompPlaneROS::setName > {
  static const char* value()
  {
    return "8ba0cf4e3278e5a4204be7ea0bd74922";
  }

  static const char* value(const ::RoboCompPlaneROS::setName&) { return value(); }
};

template<>
struct DataType< ::RoboCompPlaneROS::setName > {
  static const char* value()
  {
    return "RoboCompPlaneROS/setName";
  }

  static const char* value(const ::RoboCompPlaneROS::setName&) { return value(); }
};


// service_traits::MD5Sum< ::RoboCompPlaneROS::setNameRequest> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setName > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setNameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setName >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setNameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setNameRequest> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setName > 
template<>
struct DataType< ::RoboCompPlaneROS::setNameRequest>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setName >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setNameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::RoboCompPlaneROS::setNameResponse> should match 
// service_traits::MD5Sum< ::RoboCompPlaneROS::setName > 
template<>
struct MD5Sum< ::RoboCompPlaneROS::setNameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::RoboCompPlaneROS::setName >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setNameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::RoboCompPlaneROS::setNameResponse> should match 
// service_traits::DataType< ::RoboCompPlaneROS::setName > 
template<>
struct DataType< ::RoboCompPlaneROS::setNameResponse>
{
  static const char* value()
  {
    return DataType< ::RoboCompPlaneROS::setName >::value();
  }
  static const char* value(const ::RoboCompPlaneROS::setNameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_SETNAME_H
