// Generated by gencpp from file RoboCompPlaneROS/Dimensions.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_DIMENSIONS_H
#define ROBOCOMPPLANEROS_MESSAGE_DIMENSIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace RoboCompPlaneROS
{
template <class ContainerAllocator>
struct Dimensions_
{
  typedef Dimensions_<ContainerAllocator> Type;

  Dimensions_()
    : width(0)
    , height(0)  {
    }
  Dimensions_(const ContainerAllocator& _alloc)
    : width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> const> ConstPtr;

}; // struct Dimensions_

typedef ::RoboCompPlaneROS::Dimensions_<std::allocator<void> > Dimensions;

typedef boost::shared_ptr< ::RoboCompPlaneROS::Dimensions > DimensionsPtr;
typedef boost::shared_ptr< ::RoboCompPlaneROS::Dimensions const> DimensionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RoboCompPlaneROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/msg'], 'RoboCompPlaneROS': ['./src']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4069c3fe743f7881e847e9b0ab5556a";
  }

  static const char* value(const ::RoboCompPlaneROS::Dimensions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4069c3fe743f788ULL;
  static const uint64_t static_value2 = 0x1e847e9b0ab5556aULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompPlaneROS/Dimensions";
  }

  static const char* value(const ::RoboCompPlaneROS::Dimensions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 width\n\
int32 height\n\
";
  }

  static const char* value(const ::RoboCompPlaneROS::Dimensions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dimensions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompPlaneROS::Dimensions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompPlaneROS::Dimensions_<ContainerAllocator>& v)
  {
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_DIMENSIONS_H
