// Generated by gencpp from file RoboCompPlaneROS/Points.msg
// DO NOT EDIT!


#ifndef ROBOCOMPPLANEROS_MESSAGE_POINTS_H
#define ROBOCOMPPLANEROS_MESSAGE_POINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <RoboCompPlaneROS/PointXY.h>

namespace RoboCompPlaneROS
{
template <class ContainerAllocator>
struct Points_
{
  typedef Points_<ContainerAllocator> Type;

  Points_()
    : Points()  {
    }
  Points_(const ContainerAllocator& _alloc)
    : Points(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::RoboCompPlaneROS::PointXY_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::RoboCompPlaneROS::PointXY_<ContainerAllocator> >::other >  _Points_type;
  _Points_type Points;





  typedef boost::shared_ptr< ::RoboCompPlaneROS::Points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::RoboCompPlaneROS::Points_<ContainerAllocator> const> ConstPtr;

}; // struct Points_

typedef ::RoboCompPlaneROS::Points_<std::allocator<void> > Points;

typedef boost::shared_ptr< ::RoboCompPlaneROS::Points > PointsPtr;
typedef boost::shared_ptr< ::RoboCompPlaneROS::Points const> PointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RoboCompPlaneROS::Points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::RoboCompPlaneROS::Points_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace RoboCompPlaneROS

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/msg'], 'RoboCompPlaneROS': ['./src']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::RoboCompPlaneROS::Points_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::RoboCompPlaneROS::Points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::RoboCompPlaneROS::Points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "122189be94fdaecc98493931afe63dad";
  }

  static const char* value(const ::RoboCompPlaneROS::Points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x122189be94fdaeccULL;
  static const uint64_t static_value2 = 0x98493931afe63dadULL;
};

template<class ContainerAllocator>
struct DataType< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "RoboCompPlaneROS/Points";
  }

  static const char* value(const ::RoboCompPlaneROS::Points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PointXY[] Points\n\
\n\
================================================================================\n\
MSG: RoboCompPlaneROS/PointXY\n\
int32 x\n\
int32 y\n\
";
  }

  static const char* value(const ::RoboCompPlaneROS::Points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::RoboCompPlaneROS::Points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RoboCompPlaneROS::Points_<ContainerAllocator>& v)
  {
    s << indent << "Points[]" << std::endl;
    for (size_t i = 0; i < v.Points.size(); ++i)
    {
      s << indent << "  Points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::RoboCompPlaneROS::PointXY_<ContainerAllocator> >::stream(s, indent + "    ", v.Points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOCOMPPLANEROS_MESSAGE_POINTS_H
